tested_variables:
  source_directory: /data2/ABCD/abcd-5.0-tabular-data-extracted
  variable_default:
    filename: core/mental-health/mh_y_ksads_ss.csv
    convert:
      "555": .nan
      "888": 0
    handle_missing: invalidate
    type: unordered
    is_missing:
      - ""
      - .nan
  variable:
    ksads_1_187_t:
      description: Symptom - No two month symptom-free interval, Present
      internal_name: ksads_1_187_t
    ksads_1_188_t:
      description: Symptom - No two month symptom-free interval, Past
    ksads_22_142_t:
      description: Symptom - Insomnia, Past
    ksads_22_970_t:
      description: Diagnosis - SLEEP PROBLEMS, Past
    ksads_2_11_t:
      description: Symptom - Explosive Irritability, Past
    ksads_aud_raw_1174_t:
      filename: core/substance-use/su_y_ksads_sud.csv
      description: Alcohol Use Disorder something
target_variables:
  source_directory: /data2/ABCD/gor-images/coregistered-images
  table_of_filenames_and_metadata: /home/local/KHQ/lee.newberg/git/brain-microstructure-exploration-tools/abcdstats/src/abcdstats/abcdstats_target_variables.csv
  mask:
    filename: /data2/ABCD/gor-images/gortemplate0.nii.gz
    threshold: 0.7
  segmentation:
    filename: /home/local/KHQ/lee.newberg/git/brain-microstructure-exploration-tools/abcd-data-exploration/prototype/segmentation_data_mrtrix.seg.nrrd
    background_index: 0
  background:
    filename: /data2/ABCD/gor-images/gortemplate0.nii.gz
confounding_variables:
  source_directory: /data2/ABCD/abcd-5.0-tabular-data-extracted/core
  variable_default:
    handle_missing: invalidate
    type: unordered
    minimum_perplexity: 1.1
    longitudinal:
      - intercept
  variable:
    interview_age:
      filename: abcd-general/abcd_y_lt.csv
      internal_name: interview_age
      type: ordered
      longitudinal:
        - intercept
        - slope
    site_id_l:
      filename: abcd-general/abcd_y_lt.csv
      handle_missing: together
    demo_gender_id_v2:
      filename: gender-identity-sexual-health/gish_p_gi.csv
      convert:
        "777": ""
        "999": ""
    rel_family_id:
      filename: abcd-general/abcd_y_lt.csv
      handle_missing: together
output:
  destination_directory: "TODO:"
  local_maxima:
    minimum_peak: 0.1
    minimum_radius: 3
